spring:
  config:
    activate:
      on-profile: dev
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/realms/myrealm
  
  cloud:
    consul:
      config:
        fail-fast: false # if not in "prod" profile, do not force to use Spring Cloud Config
        format: yaml
        profile-separator: '-'
      discovery:
        prefer-ip-address: true
        tags:
          - profile=${spring.profiles.active}
          - version='@project.version@'
          - git-version=${git.commit.id.describe:}
          - git-commit=${git.commit.id.abbrev:}
          - git-branch=${git.branch:}
      host: consul
      port: 8500
  cache:
    type: redis
  redis:
    host: redis
    port: 6379

  liquibase:
    enabled: false   
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

logging:
  level:
    root: INFO
    com.sample: DEBUG
    org.springframework.cloud.config.client: DEBUG
    org.springframework.cloud.vault: DEBUG

server:
  port: 8090
  address: 0.0.0.0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    # url: http://localhost:8090/v3/api-docs
    path: /swagger-ui.html
    oauth2-redirect-url: http://localhost:8090/swagger-ui/oauth2-redirect.html
    oauth:
      client-id: ${swagger-ui.oauth.client-id}
      client-secret: ${swagger-ui.oauth.client-secret}
      authorization-url: ${swagger-ui.oauth.authorization-url}
      token-url: ${swagger-ui.oauth.token-url}
      scope: ${swagger-ui.oauth.scope}


jwt:
  secret: 4a7f1a9c4a3f4d7a8fbc7d6f25d9918b6d7cdd2ef9e3c3c512e1ef98d9ff2d60




