spring:
  config:
    activate:
      on-profile: dev

  cloud:
    consul:
      config:
        fail-fast: false # if not in "prod" profile, do not force to use Spring Cloud Config
        format: yaml
        profile-separator: '-'
      discovery:
        prefer-ip-address: true
        tags:
          - profile=${spring.profiles.active}
          - version='@project.version@'
          - git-version=${git.commit.id.describe:}
          - git-commit=${git.commit.id.abbrev:}
          - git-branch=${git.branch:}
      host: localhost
      port: 8500
    # datasoure:
    #   password: ${spring.datasource.password}

  # datasource:
  #   type: com.zaxxer.hikari.HikariDataSource
  #   url: jdbc:postgresql://localhost:5433/microProject?currentSchema=public
  #   username: microProject
  #   password: 
  #   hikari:
  #     poolName: Hikari
  #     auto-commit: false

  # jpa:
  #   hibernate:
  #     dialect: org.hibernate.dialect.PostgreSQLDialect
  #     ddl-auto: update
  #   show-sql: true
  # datasource:
  #   type: com.zaxxer.hikari.HikariDataSource
  #   url:  jdbc:mysql://localhost:3307/microProject?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  #   username: microProject
  #   password: microProject
  #   hikari:
  #     pool-name: Hikari
  #     auto-commit: false
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: false   
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

logging:
  level:
    root: INFO
    com.sample: DEBUG
    org.springframework.cloud.config.client: DEBUG
    org.springframework.cloud.vault: DEBUG

server:
  port: 8080

jwt:
  secret: 4a7f1a9c4a3f4d7a8fbc7d6f25d9918b6d7cdd2ef9e3c3c512e1ef98d9ff2d60

